In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
import statsmodels.api as sm
import statsmodels as sms
import seaborn as sns
import statsmodels.formula.api as smf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
revised_data_us_zips=pd.read_csv("revised_data_us_zips.csv")
revised_loopnet_data_ca = pd.read_csv("revised_loopnet_data_ca.csv")

merged = pd.merge(left = revised_loopnet_data_ca, right = revised_data_us_zips, left_on = "zip" ,
                   right_on ="zip", how = "outer")
merged

,id_x,zip,address,price_usd,size_sf,no_stories,property_type,year_built,year_renovated,parking_ratio,...,gross_rent_multiplier,id_y,city,state_id,state_name,density,county_name,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,1.0,90066,"4077 McLaughlin Ave, Los Angeles, CA 90066 - M...",3895000,8156,2,Multifamily,1964,\N,1.72,...,14.35,30059,Los Angeles,CA,California,4642,Los Angeles,NaN,NaN,NaN
1,14.0,90066,"3451 Beethoven St, Los Angeles, CA 90066 - Mul...",2000000,2700,2,Multifamily,1961,\N,1.11,...,18,30059,Los Angeles,CA,California,4642,Los Angeles,NaN,NaN,NaN
2,67.0,90066,"3814 Lyceum Ave, Los Angeles, CA 90066 - Multi...",1395000,1624,1,Multifamily,1953,\N,\N,...,\N,30059,Los Angeles,CA,California,4642,Los Angeles,NaN,NaN,NaN
3,74.0,90066,"4417 Campbell Dr, Los Angeles, CA 90066 - Mult...",2350000,3646,2,Multifamily,1928,1990,1.1,...,13.46,30059,Los Angeles,CA,California,4642,Los Angeles,NaN,NaN,NaN
4,161.0,90066,"3611 S Centinela Ave, Los Angeles, CA 90066 - ...",4150000,7266,2,Multifamily,1988,\N,2.2,...,16.2,30059,Los Angeles,CA,California,4642,Los Angeles,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11904,NaN,99923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,33117,Hyder,AK,Alaska,0.3,Prince of Wales-Hyder,NaN,NaN,NaN
11905,NaN,99925,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,33118,Klawock,AK,Alaska,6.3,Prince of Wales-Hyder,NaN,NaN,NaN
11906,NaN,99926,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,33119,Metlakatla,AK,Alaska,4.8,Prince of Wales-Hyder,NaN,NaN,NaN
11907,NaN,99927,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,33120,Point Baker,AK,Alaska,0,Prince of Wales-Hyder,NaN,NaN,NaN
11908,NaN,99929,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,33121,Wrangell,AK,Alaska,0.4,Wrangell,NaN,NaN,NaN

In [3]:
merged=merged.replace(to_replace="\\N",value=np.nan)
merged.replace([np.inf, -np.inf], np.nan, inplace = True)
merged.drop(["Unnamed: 7","Unnamed: 8","Unnamed: 9","year_renovated"],
        axis=1,inplace=True)
merged.dropna(inplace = True)

merged

,id_x,zip,address,price_usd,size_sf,no_stories,property_type,year_built,parking_ratio,no_units,lot_size_ac,building_class,cap_rate,gross_rent_multiplier,id_y,city,state_id,state_name,density,county_name
0,1.0,90066,"4077 McLaughlin Ave, Los Angeles, CA 90066 - M...",3895000,8156,2,Multifamily,1964,1.72,10,0.16,B,4.88,14.35,30059,Los Angeles,CA,California,4642,Los Angeles
4,161.0,90066,"3611 S Centinela Ave, Los Angeles, CA 90066 - ...",4150000,7266,2,Multifamily,1988,2.2,9,0.15,B,3.98,16.2,30059,Los Angeles,CA,California,4642,Los Angeles
15,927.0,90066,"12747 Mitchell Ave, Los Angeles, CA 90066 - Mu...",2195000,3062,1,Multifamily,1962,1.96,5,0.16,C,3,22.88,30059,Los Angeles,CA,California,4642,Los Angeles
54,166435.0,90066,"4320 S Centinela Ave, Los Angeles, CA 90066 - ...",7995000,21268,3,Multifamily,1990,0.71,15,0.24,B,3.45,16.92,30059,Los Angeles,CA,California,4642,Los Angeles
58,168418.0,90066,"11411 Washington Pl, Los Angeles, CA 90066 - M...",1600000,3000,2,Multifamily,1952,1.33,4,0.11,C,3.26,18.28,30059,Los Angeles,CA,California,4642,Los Angeles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8625,166269.0,91501,"550 E Providencia Ave, Burbank, CA 91501 - Mul...",2300000,5768,2,Multifamily,1977,0.87,5,0.16,C,3.53,18.8,30250,Burbank,CA,California,1996.1,Los Angeles
8626,166270.0,91501,"603 S 6th St, Burbank, CA 91501 - FULLY RENOVA...",999000,2026,1,Multifamily,1948,1.48,2,0.16,C,4.52,16.17,30250,Burbank,CA,California,1996.1,Los Angeles
8893,164355.0,90270,"5418 Gifford Ave, Maywood, CA 90270 - Multifam...",795000,1728,1,Multifamily,1936,3.47,3,0.14,C,5.75,13.52,30095,Maywood,CA,California,8350.2,Los Angeles
8905,175530.0,90240,"7348-7350 Florence Avenue, Downey, CA 90240 - ...",5500000,15576,2,Multifamily,1960,2.57,20,0.94,C,4.08,14.5,30080,Downey,CA,California,3464.1,Los Angeles
9060,103913.0,90002,"8804-8806 Beach St, Los Angeles, CA 90002 - Mu...",1200000,2848,1,Multifamily,1924,4.21,6,0.2,C,6.16,12.35,30004,Los Angeles,CA,California,6721.1,Los Angeles

In [4]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 692 entries, 0 to 9060
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id_x                   692 non-null    float64
 1   zip                    692 non-null    int64
 2   address                692 non-null    object
 3   price_usd              692 non-null    object
 4   size_sf                692 non-null    object
 5   no_stories             692 non-null    object
 6   property_type          692 non-null    object
 7   year_built             692 non-null    object
 8   parking_ratio          692 non-null    object
 9   no_units               692 non-null    object
 10  lot_size_ac            692 non-null    object
 11  building_class         692 non-null    object
 12  cap_rate               692 non-null    object
 13  gross_rent_multiplier  692 non-null    object
 14  id_y                   692 non-null    int64
 15  city                   692 non-null    object
 16  state_id               692 non-null    object
 17  state_name             692 non-null    object
 18  density                692 non-null    object
 19  county_name            692 non-null    object
dtypes: float64(1), int64(2), object(17)
memory usage: 113.5+ KB

In [5]:
df=merged.copy()
df.iloc[:,3:6]=df.iloc[:,3:6].astype('float')
df.iloc[:,7:11]=df.iloc[:,7:11].astype('float')
df.iloc[:,12:14]=df.iloc[:,12:14].astype('float')
df.iloc[:,18]=df.iloc[:,18].astype('float')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 692 entries, 0 to 9060
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id_x                   692 non-null    float64
 1   zip                    692 non-null    int64
 2   address                692 non-null    object
 3   price_usd              692 non-null    float64
 4   size_sf                692 non-null    float64
 5   no_stories             692 non-null    float64
 6   property_type          692 non-null    object
 7   year_built             692 non-null    float64
 8   parking_ratio          692 non-null    float64
 9   no_units               692 non-null    float64
 10  lot_size_ac            692 non-null    float64
 11  building_class         692 non-null    object
 12  cap_rate               692 non-null    float64
 13  gross_rent_multiplier  692 non-null    float64
 14  id_y                   692 non-null    int64
 15  city                   692 non-null    object
 16  state_id               692 non-null    object
 17  state_name             692 non-null    object
 18  density                692 non-null    float64
 19  county_name            692 non-null    object
dtypes: float64(11), int64(2), object(7)
memory usage: 113.5+ KB

## Decision Tree

In [7]:
x = df.values[:, [4,5,7,8,9,10,12,13,18]]
y = df.values[:,3]

In [8]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
model = regressor.fit(x, y)

In [9]:
## It can't be predicted using all indpendent variables, thus, we use the size_sf as the most signifcant predictor

In [10]:
X = df.values[:, 4:5]
Y = df.values[:, 3]
Y.reshape(-1,1)
X.reshape(-1,1)

array([[8156.0],
       [7266.0],
       [3062.0],
       [21268.0],
       [3000.0],
       [7000.0],
       [4986.0],
       [14789.0],
       [14223.0],
       [13201.0],
       [5709.0],
       [13201.0],
       [31845.0],
       [13232.0],
       [10788.0],
       [7358.0],
       [6879.0],
       [15480.0],
       [5312.0],
       [9158.0],
       [4626.0],
       [8812.0],
       [4600.0],
       [4712.0],
       [4212.0],
       [2952.0],
       [6201.0],
       [5000.0],
       [9453.0],
       [5862.0],
       [7566.0],
       [10276.0],
       [9658.0],
       [7712.0],
       [7712.0],
       [9658.0],
       [5060.0],
       [4928.0],
       [4300.0],
       [5624.0],
       [5043.0],
       [12502.0],
       [1959.0],
       [4928.0],
       [4928.0],
       [7972.0],
       [5188.0],
       [6915.0],
       [5260.0],
       [4530.0],
       [19674.0],
       [17674.0],
       [2832.0],
       [18660.0],
       [2980.0],
       [3434.0],
       [5619.0],
       [5552.0],
       [4256.0],
       [17063.0],
       [3527.0],
       [6018.0],
       [1854.0],
       [11841.0],
       [5664.0],
       [3008.0],
       [9926.0],
       [6512.0],
       [5262.0],
       [4432.0],
       [4000.0],
       [14000.0],
       [5553.0],
       [5046.0],
       [14000.0],
       [5402.0],
       [4312.0],
       [7924.0],
       [2365.0],
       [5796.0],
       [17660.0],
       [3110.0],
       [8710.0],
       [9888.0],
       [13924.0],
       [6800.0],
       [4148.0],
       [5020.0],
       [4231.0],
       [32139.0],
       [5621.0],
       [4032.0],
       [5758.0],
       [19108.0],
       [1904.0],
       [7523.0],
       [6800.0],
       [20445.0],
       [11233.0],
       [3600.0],
       [6830.0],
       [4424.0],
       [4900.0],
       [17444.0],
       [2019.0],
       [2712.0],
       [3204.0],
       [2576.0],
       [1730.0],
       [22922.0],
       [4954.0],
       [5028.0],
       [12395.0],
       [6720.0],
       [14565.0],
       [5028.0],
       [44692.0],
       [2863.0],
       [4982.0],
       [5517.0],
       [16088.0],
       [20480.0],
       [4209.0],
       [4371.0],
       [4133.0],
       [4494.0],
       [3027.0],
       [3623.0],
       [3782.0],
       [14994.0],
       [24872.0],
       [4924.0],
       [6210.0],
       [4881.0],
       [3559.0],
       [8900.0],
       [13104.0],
       [13120.0],
       [18476.0],
       [2366.0],
       [3900.0],
       [4334.0],
       [4221.0],
       [5577.0],
       [2883.0],
       [4904.0],
       [7100.0],
       [4800.0],
       [9305.0],
       [10320.0],
       [2547.0],
       [3296.0],
       [4188.0],
       [5280.0],
       [3574.0],
       [4754.0],
       [11958.0],
       [5368.0],
       [14764.0],
       [2992.0],
       [10656.0],
       [3881.0],
       [3816.0],
       [4696.0],
       [4034.0],
       [29096.0],
       [5902.0],
       [1775.0],
       [4076.0],
       [6046.0],
       [2620.0],
       [5093.0],
       [3036.0],
       [7180.0],
       [5093.0],
       [5288.0],
       [5058.0],
       [3816.0],
       [5535.0],
       [4790.0],
       [7550.0],
       [8890.0],
       [6101.0],
       [7824.0],
       [5046.0],
       [3926.0],
       [6339.0],
       [7215.0],
       [3968.0],
       [6130.0],
       [3870.0],
       [7824.0],
       [3711.0],
       [7440.0],
       [9868.0],
       [6435.0],
       [10916.0],
       [8226.0],
       [25184.0],
       [8190.0],
       [5022.0],
       [12444.0],
       [7922.0],
       [6756.0],
       [18252.0],
       [29310.0],
       [209716.0],
       [5148.0],
       [40502.0],
       [13452.0],
       [7097.0],
       [3374.0],
       [5270.0],
       [10444.0],
       [9942.0],
       [6384.0],
       [4992.0],
       [8571.0],
       [63324.0],
       [11915.0],
       [19516.0],
       [5386.0],
       [6754.0],
       [7110.0],
       [6900.0],
       [5511.0],
       [6756.0],
       [13977.0],
       [10951.0],
       [4585.0],
       [10860.0],
       [8812.0],
       [8209.0],
       [2800.0],
       [1751.0],
       [2402.0],
       [3120.0],
       [2006.0],
       [3288.0],
       [3567.0],
       [2832.0],
       [11338.0],
       [6339.0],
       [3398.0],
       [11888.0],
       [4528.0],
       [2743.0],
       [3216.0],
       [6243.0],
       [5637.0],
       [3904.0],
       [10054.0],
       [3920.0],
       [10185.0],
       [2847.0],
       [10164.0],
       [4323.0],
       [4093.0],
       [2759.0],
       [3692.0],
       [6387.0],
       [4568.0],
       [8230.0],
       [10338.0],
       [14355.0],
       [12146.0],
       [7172.0],
       [5825.0],
       [37000.0],
       [11512.0],
       [8456.0],
       [12718.0],
       [3977.0],
       [10396.0],
       [8206.0],
       [6948.0],
       [7592.0],
       [6727.0],
       [7159.0],
       [7550.0],
       [3840.0],
       [13790.0],
       [13790.0],
       [7550.0],
       [3952.0],
       [4782.0],
       [6372.0],
       [3780.0],
       [4268.0],
       [5520.0],
       [4111.0],
       [6387.0],
       [15813.0],
       [7316.0],
       [7159.0],
       [14880.0],
       [6611.0],
       [15130.0],
       [9464.0],
       [4932.0],
       [7211.0],
       [6066.0],
       [3880.0],
       [7586.0],
       [5112.0],
       [17610.0],
       [8107.0],
       [7158.0],
       [5922.0],
       [6408.0],
       [6123.0],
       [3888.0],
       [23399.0],
       [4616.0],
       [26715.0],
       [6620.0],
       [16482.0],
       [3700.0],
       [19712.0],
       [3214.0],
       [9836.0],
       [6937.0],
       [5952.0],
       [4121.0],
       [6620.0],
       [8096.0],
       [8149.0],
       [4350.0],
       [4354.0],
       [3618.0],
       [5024.0],
       [5590.0],
       [12088.0],
       [2840.0],
       [61886.0],
       [4685.0],
       [7741.0],
       [7704.0],
       [8193.0],
       [20912.0],
       [9554.0],
       [9042.0],
       [2819.0],
       [18708.0],
       [3896.0],
       [7497.0],
       [3902.0],
       [6752.0],
       [3964.0],
       [3112.0],
       [10576.0],
       [4042.0],
       [3750.0],
       [16774.0],
       [5996.0],
       [20168.0],
       [17718.0],
       [2327.0],
       [8965.0],
       [9286.0],
       [2550.0],
       [6094.0],
       [5170.0],
       [4860.0],
       [3000.0],
       [6610.0],
       [6693.0],
       [17708.0],
       [1584.0],
       [15918.0],
       [13536.0],
       [4109.0],
       [4093.0],
       [2911.0],
       [3728.0],
       [4408.0],
       [4028.0],
       [6876.0],
       [7029.0],
       [13924.0],
       [22996.0],
       [2853.0],
       [3424.0],
       [2864.0],
       [3898.0],
       [2853.0],
       [4300.0],
       [3328.0],
       [3025.0],
       [3996.0],
       [4128.0],
       [2754.0],
       [10556.0],
       [3312.0],
       [4086.0],
       [3017.0],
       [3329.0],
       [2438.0],
       [6240.0],
       [4000.0],
       [2100.0],
       [7288.0],
       [10925.0],
       [5308.0],
       [10158.0],
       [14180.0],
       [6354.0],
       [10882.0],
       [6694.0],
       [4400.0],
       [3574.0],
       [4474.0],
       [4646.0],
       [4504.0],
       [23044.0],
       [9576.0],
       [15992.0],
       [4318.0],
       [21879.0],
       [11972.0],
       [18009.0],
       [23994.0],
       [40801.0],
       [8255.0],
       [23606.0],
       [71004.0],
       [3339.0],
       [9293.0],
       [24428.0],
       [15990.0],
       [27903.0],
       [29536.0],
       [26450.0],
       [8907.0],
       [12925.0],
       [9532.0],
       [41756.0],
       [13740.0],
       [7962.0],
       [5073.0],
       [17050.0],
       [13056.0],
       [6850.0],
       [24480.0],
       [14204.0],
       [5966.0],
       [10310.0],
       [10357.0],
       [1732.0],
       [6964.0],
       [7110.0],
       [5418.0],
       [3800.0],
       [1672.0],
       [8118.0],
       [6627.0],
       [81243.0],
       [4470.0],
       [3336.0],
       [4706.0],
       [1948.0],
       [4096.0],
       [6964.0],
       [5760.0],
       [4128.0],
       [3087.0],
       [12172.0],
       [9164.0],
       [7742.0],
       [8634.0],
       [5404.0],
       [5898.0],
       [3998.0],
       [9196.0],
       [12820.0],
       [20876.0],
       [15110.0],
       [4685.0],
       [9078.0],
       [4503.0],
       [11880.0],
       [3421.0],
       [4917.0],
       [2773.0],
       [2995.0],
       [2400.0],
       [3310.0],
       [6914.0],
       [5807.0],
       [8300.0],
       [4930.0],
       [4542.0],
       [3940.0],
       [6304.0],
       [5438.0],
       [5634.0],
       [6040.0],
       [18188.0],
       [3432.0],
       [6525.0],
       [7662.0],
       [10974.0],
       [26763.0],
       [7500.0],
       [4730.0],
       [6035.0],
       [10974.0],
       [20358.0],
       [23763.0],
       [5086.0],
       [5224.0],
       [15007.0],
       [74536.0],
       [6068.0],
       [3520.0],
       [8102.0],
       [3520.0],
       [11492.0],
       [6309.0],
       [15908.0],
       [6288.0],
       [2000.0],
       [2328.0],
       [12769.0],
       [13368.0],
       [6690.0],
       [8984.0],
       [7492.0],
       [19002.0],
       [1802.0],
       [4764.0],
       [4849.0],
       [2979.0],
       [3032.0],
       [5132.0],
       [6452.0],
       [4504.0],
       [5331.0],
       [4736.0],
       [5375.0],
       [4886.0],
       [4736.0],
       [9984.0],
       [2970.0],
       [6128.0],
       [52231.0],
       [4498.0],
       [5703.0],
       [4962.0],
       [33028.0],
       [20748.0],
       [29884.0],
       [3715.0],
       [4227.0],
       [3832.0],
       [8085.0],
       [3649.0],
       [4138.0],
       [2677.0],
       [8628.0],
       [4140.0],
       [13778.0],
       [2593.0],
       [24864.0],
       [11175.0],
       [10168.0],
       [8628.0],
       [24722.0],
       [3766.0],
       [15138.0],
       [7539.0],
       [2920.0],
       [6819.0],
       [2096.0],
       [8062.0],
       [1024.0],
       [5762.0],
       [8644.0],
       [3712.0],
       [2102.0],
       [1984.0],
       [19448.0],
       [5346.0],
       [6362.0],
       [16736.0],
       [10955.0],
       [7144.0],
       [9979.0],
       [12015.0],
       [24801.0],
       [4436.0],
       [3704.0],
       [5728.0],
       [7452.0],
       [2468.0],
       [5512.0],
       [4955.0],
       [16056.0],
       [3888.0],
       [3658.0],
       [2853.0],
       [5254.0],
       [5103.0],
       [3409.0],
       [5512.0],
       [5600.0],
       [5229.0],
       [19909.0],
       [6852.0],
       [3405.0],
       [28958.0],
       [5416.0],
       [7132.0],
       [2536.0],
       [8326.0],
       [28285.0],
       [20731.0],
       [2849.0],
       [5402.0],
       [3064.0],
       [5255.0],
       [4864.0],
       [6953.0],
       [4092.0],
       [28742.0],
       [4656.0],
       [12958.0],
       [15281.0],
       [4380.0],
       [3139.0],
       [3616.0],
       [14489.0],
       [6560.0],
       [9398.0],
       [11398.0],
       [18344.0],
       [4834.0],
       [4466.0],
       [5800.0],
       [5881.0],
       [11000.0],
       [5448.0],
       [7512.0],
       [4780.0],
       [4780.0],
       [5369.0],
       [4492.0],
       [4174.0],
       [4100.0],
       [5942.0],
       [20456.0],
       [3288.0],
       [2216.0],
       [3693.0],
       [3127.0],
       [7440.0],
       [2343.0],
       [3760.0],
       [6380.0],
       [27969.0],
       [3843.0],
       [4420.0],
       [8640.0],
       [4004.0],
       [8577.0],
       [13546.0],
       [6882.0],
       [11116.0],
       [4420.0],
       [3570.0],
       [3420.0],
       [11867.0],
       [28640.0],
       [5419.0],
       [12713.0],
       [5964.0],
       [3998.0],
       [10288.0],
       [19102.0],
       [7898.0],
       [5136.0],
       [8489.0],
       [5368.0],
       [13440.0],
       [7603.0],
       [36493.0],
       [6871.0],
       [5768.0],
       [2026.0],
       [1728.0],
       [15576.0],
       [2848.0]], dtype=object)

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train, Y_train)

DecisionTreeRegressor(random_state=0)

In [14]:
Y_pred = regressor.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[3100000.0 2625000.0]
 [2650000.0 950000.0]
 [2750000.0 3250000.0]
 [1250000.0 949949.0]
 [3600000.0 4700000.0]
 [3895000.0 6000000.0]
 [2000000.0 4495000.0]
 [2275000.0 1200000.0]
 [3295000.0 2345000.0]
 [4900000.0 1280000.0]
 [4150000.0 4895000.0]
 [9650000.0 10300000.0]
 [5064000.0 6950000.0]
 [5450000.0 3325000.0]
 [875000.0 1850000.0]
 [2175000.0 1499000.0]
 [3795000.0 4150000.0]
 [1850000.0 1450000.0]
 [1300000.0 1150000.0]
 [2296000.0 1725000.0]
 [6950000.0 2725000.0]
 [12900000.0 11850000.0]
 [4100000.0 5750000.0]
 [7000000.0 7500000.0]
 [6995000.0 6550000.0]
 [3550000.0 5600000.0]
 [2395000.0 3850000.0]
 [2175000.0 1795000.0]
 [6995000.0 2200000.0]
 [1600000.0 3495000.0]
 [774999.0 595000.0]
 [1200000.0 1475000.0]
 [5295000.0 5445000.0]
 [7250000.0 3295000.0]
 [1750000.0 1900000.0]
 [2695000.0 3200000.0]
 [1560000.0 1700000.0]
 [2850000.0 4800000.0]
 [2700000.0 2800000.0]
 [11880000.0 7500000.0]
 [3200000.0 1720000.0]
 [2750000.0 3250000.0]
 [675000.0 999000.0]
 [1550000.0 2495000.0]
 [2195000.0 2480000.0]
 [1395000.0 1695000.0]
 [6800000.0 5650000.0]
 [5195000.0 4250000.0]
 [3250000.0 2400000.0]
 [1450000.0 1350000.0]
 [3100000.0 3795000.0]
 [2120000.0 4075000.0]
 [1395000.0 1795000.0]
 [8950000.0 6350000.0]
 [3999000.0 6890000.0]
 [2150000.0 1699000.0]
 [3200000.0 3100000.0]
 [2280000.0 1500000.0]
 [1595000.0 1800000.0]
 [2200000.0 2950000.0]
 [729900.0 795000.0]
 [6950000.0 3700000.0]
 [9975000.0 10000000.0]
 [5650000.0 9250000.0]
 [1795000.0 2895000.0]
 [1575000.0 1995000.0]
 [2550000.0 1350000.0]
 [2022500.0 2950000.0]
 [2350000.0 2150000.0]
 [15950000.0 19500000.0]
 [2499000.0 1695000.0]
 [3950000.0 3500000.0]
 [7250000.0 7250000.0]
 [2795000.0 1395000.0]
 [1599000.0 875000.0]
 [1949000.0 2000000.0]
 [7500000.0 2695000.0]
 [3775000.0 3595000.0]
 [2850000.0 3250000.0]
 [2099000.0 3350000.0]
 [2750000.0 1650000.0]
 [7250000.0 3499000.0]
 [7800000.0 6250000.0]
 [7250000.0 3295000.0]
 [2475000.0 2650000.0]
 [4900000.0 1856000.0]
 [2750000.0 2125000.0]
 [3212500.0 1350000.0]
 [1965000.0 1885000.0]
 [1795000.0 3489500.0]
 [1425000.0 1750000.0]
 [2995000.0 1299000.0]
 [2296000.0 3290000.0]
 [2500000.0 2875000.0]
 [2950000.0 1300000.0]
 [1395000.0 1199000.0]
 [6500000.0 3895000.0]
 [4100000.0 2085000.0]
 [5650000.0 4500000.0]
 [21500000.0 3950000.0]
 [2750000.0 3200000.0]
 [3097500.0 2749000.0]
 [1750000.0 1850000.0]
 [2400000.0 2550000.0]
 [2100000.0 1595000.0]
 [1625000.0 1980000.0]
 [12900000.0 12000000.0]
 [12900000.0 23500000.0]
 [1595000.0 1550000.0]
 [2375000.0 4450000.0]
 [1949000.0 4500000.0]
 [2895000.0 3695000.0]
 [1598000.0 3195000.0]
 [2750000.0 1450000.0]
 [2000000.0 1525000.0]
 [6425000.0 6295000.0]
 [1600000.0 2899000.0]
 [2497000.0 1479000.0]
 [4900000.0 2650000.0]
 [865000.0 1100000.0]
 [3995000.0 3995000.0]
 [4775000.0 3400000.0]
 [8875000.0 6950000.0]
 [2150000.0 1640000.0]
 [5500000.0 9000000.0]
 [4150000.0 5500000.0]
 [6535000.0 7050000.0]
 [850000.0 849900.0]
 [2100000.0 4995000.0]
 [2030000.0 1449000.0]
 [2000000.0 3950000.0]
 [2500000.0 3200000.0]
 [3400000.0 2050000.0]
 [1550000.0 2000000.0]
 [4300000.0 1650000.0]
 [1895000.0 1250000.0]
 [1195000.0 1450000.0]
 [1490000.0 1795000.0]
 [780000.0 945000.0]
 [3936945.0 3800000.0]
 [3650000.0 2000000.0]
 [1410000.0 1995000.0]
 [1625000.0 1600000.0]
 [3545000.0 3575000.0]
 [2695000.0 3799000.0]
 [6950000.0 6700000.0]
 [7250000.0 1650000.0]
 [6795000.0 6795000.0]
 [2295000.0 2950000.0]
 [2550000.0 3095000.0]
 [4775000.0 3600000.0]
 [998000.0 2895000.0]
 [7250000.0 3400000.0]
 [2950000.0 2399000.0]
 [1350000.0 1650000.0]
 [2550000.0 1295000.0]
 [3650000.0 3395000.0]
 [3795000.0 3250000.0]
 [6995000.0 8100000.0]
 [1425000.0 1150000.0]
 [2350000.0 3190000.0]
 [12500000.0 11025000.0]
 [2195000.0 3550000.0]
 [3950000.0 4575000.0]
 [4100000.0 6995000.0]
 [2695000.0 7500000.0]
 [8850000.0 6100000.0]
 [2750000.0 2600000.0]
 [6760000.0 6760000.0]
 [3999000.0 3999000.0]
 [2149000.0 1790000.0]
 [12900000.0 14250000.0]
 [1345000.0 1850000.0]]

In [15]:
df3 = Y_pred - Y_test
df3.sort()
df3

array([-10600000.0, -4805000.0, -3600000.0, -3550000.0, -3500000.0,
       -2895000.0, -2895000.0, -2891000.0, -2551000.0, -2495000.0,
       -2105000.0, -2075000.0, -2050000.0, -1955000.0, -1950000.0,
       -1950000.0, -1897000.0, -1895000.0, -1886000.0, -1694500.0,
       -1650000.0, -1597000.0, -1455000.0, -1355000.0, -1350000.0,
       -1350000.0, -1299000.0, -1251000.0, -1105000.0, -1104000.0,
       -1100000.0, -1100000.0, -994000.0, -975000.0, -945000.0, -927500.0,
       -840000.0, -800000.0, -750000.0, -745000.0, -700000.0, -695000.0,
       -655000.0, -650000.0, -625000.0, -585000.0, -545000.0, -515000.0,
       -505000.0, -505000.0, -500000.0, -500000.0, -500000.0, -450000.0,
       -450000.0, -420000.0, -400000.0, -400000.0, -375000.0, -355000.0,
       -355000.0, -325000.0, -324000.0, -305000.0, -300000.0, -300000.0,
       -285000.0, -275000.0, -255000.0, -235000.0, -205000.0, -175000.0,
       -165000.0, -150000.0, -150000.0, -150000.0, -140000.0, -100000.0,
       -100000.0, -65100.0, -51000.0, -30000.0, -25000.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 100.0, 25000.0, 45000.0, 80000.0, 100000.0, 100000.0,
       130000.0, 136945.0, 150000.0, 150000.0, 179999.0, 180000.0,
       196000.0, 200000.0, 250000.0, 255000.0, 275000.0, 300051.0,
       348500.0, 359000.0, 380000.0, 400000.0, 445000.0, 450000.0,
       451000.0, 475000.0, 475000.0, 505000.0, 510000.0, 545000.0,
       551000.0, 571000.0, 581000.0, 625000.0, 645000.0, 676000.0,
       724000.0, 780000.0, 804000.0, 850000.0, 900000.0, 945000.0,
       950000.0, 1018000.0, 1050000.0, 1075000.0, 1100000.0, 1150000.0,
       1150000.0, 1175000.0, 1200000.0, 1255000.0, 1300000.0, 1350000.0,
       1375000.0, 1400000.0, 1475000.0, 1480000.0, 1550000.0, 1650000.0,
       1650000.0, 1696000.0, 1700000.0, 1862500.0, 1925000.0, 2015000.0,
       2125000.0, 2250000.0, 2600000.0, 2605000.0, 2650000.0, 2750000.0,
       3044000.0, 3250000.0, 3620000.0, 3751000.0, 3850000.0, 3955000.0,
       3955000.0, 4225000.0, 4380000.0, 4795000.0, 4805000.0, 5600000.0,
       17550000.0], dtype=object)

## Random Forest

In [16]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(x, y)

RandomForestRegressor(n_estimators=10, random_state=0)

In [17]:
## using the size square feet as the predictor

In [18]:
from sklearn.ensemble import RandomForestRegressor
regressor1 = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor1.fit(X, Y)

RandomForestRegressor(n_estimators=10, random_state=0)

In [19]:
Y_pred1 = regressor1.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[3100000.0 2625000.0]
 [2650000.0 950000.0]
 [2750000.0 3250000.0]
 [1250000.0 949949.0]
 [3600000.0 4700000.0]
 [3895000.0 6000000.0]
 [2000000.0 4495000.0]
 [2275000.0 1200000.0]
 [3295000.0 2345000.0]
 [4900000.0 1280000.0]
 [4150000.0 4895000.0]
 [9650000.0 10300000.0]
 [5064000.0 6950000.0]
 [5450000.0 3325000.0]
 [875000.0 1850000.0]
 [2175000.0 1499000.0]
 [3795000.0 4150000.0]
 [1850000.0 1450000.0]
 [1300000.0 1150000.0]
 [2296000.0 1725000.0]
 [6950000.0 2725000.0]
 [12900000.0 11850000.0]
 [4100000.0 5750000.0]
 [7000000.0 7500000.0]
 [6995000.0 6550000.0]
 [3550000.0 5600000.0]
 [2395000.0 3850000.0]
 [2175000.0 1795000.0]
 [6995000.0 2200000.0]
 [1600000.0 3495000.0]
 [774999.0 595000.0]
 [1200000.0 1475000.0]
 [5295000.0 5445000.0]
 [7250000.0 3295000.0]
 [1750000.0 1900000.0]
 [2695000.0 3200000.0]
 [1560000.0 1700000.0]
 [2850000.0 4800000.0]
 [2700000.0 2800000.0]
 [11880000.0 7500000.0]
 [3200000.0 1720000.0]
 [2750000.0 3250000.0]
 [675000.0 999000.0]
 [1550000.0 2495000.0]
 [2195000.0 2480000.0]
 [1395000.0 1695000.0]
 [6800000.0 5650000.0]
 [5195000.0 4250000.0]
 [3250000.0 2400000.0]
 [1450000.0 1350000.0]
 [3100000.0 3795000.0]
 [2120000.0 4075000.0]
 [1395000.0 1795000.0]
 [8950000.0 6350000.0]
 [3999000.0 6890000.0]
 [2150000.0 1699000.0]
 [3200000.0 3100000.0]
 [2280000.0 1500000.0]
 [1595000.0 1800000.0]
 [2200000.0 2950000.0]
 [729900.0 795000.0]
 [6950000.0 3700000.0]
 [9975000.0 10000000.0]
 [5650000.0 9250000.0]
 [1795000.0 2895000.0]
 [1575000.0 1995000.0]
 [2550000.0 1350000.0]
 [2022500.0 2950000.0]
 [2350000.0 2150000.0]
 [15950000.0 19500000.0]
 [2499000.0 1695000.0]
 [3950000.0 3500000.0]
 [7250000.0 7250000.0]
 [2795000.0 1395000.0]
 [1599000.0 875000.0]
 [1949000.0 2000000.0]
 [7500000.0 2695000.0]
 [3775000.0 3595000.0]
 [2850000.0 3250000.0]
 [2099000.0 3350000.0]
 [2750000.0 1650000.0]
 [7250000.0 3499000.0]
 [7800000.0 6250000.0]
 [7250000.0 3295000.0]
 [2475000.0 2650000.0]
 [4900000.0 1856000.0]
 [2750000.0 2125000.0]
 [3212500.0 1350000.0]
 [1965000.0 1885000.0]
 [1795000.0 3489500.0]
 [1425000.0 1750000.0]
 [2995000.0 1299000.0]
 [2296000.0 3290000.0]
 [2500000.0 2875000.0]
 [2950000.0 1300000.0]
 [1395000.0 1199000.0]
 [6500000.0 3895000.0]
 [4100000.0 2085000.0]
 [5650000.0 4500000.0]
 [21500000.0 3950000.0]
 [2750000.0 3200000.0]
 [3097500.0 2749000.0]
 [1750000.0 1850000.0]
 [2400000.0 2550000.0]
 [2100000.0 1595000.0]
 [1625000.0 1980000.0]
 [12900000.0 12000000.0]
 [12900000.0 23500000.0]
 [1595000.0 1550000.0]
 [2375000.0 4450000.0]
 [1949000.0 4500000.0]
 [2895000.0 3695000.0]
 [1598000.0 3195000.0]
 [2750000.0 1450000.0]
 [2000000.0 1525000.0]
 [6425000.0 6295000.0]
 [1600000.0 2899000.0]
 [2497000.0 1479000.0]
 [4900000.0 2650000.0]
 [865000.0 1100000.0]
 [3995000.0 3995000.0]
 [4775000.0 3400000.0]
 [8875000.0 6950000.0]
 [2150000.0 1640000.0]
 [5500000.0 9000000.0]
 [4150000.0 5500000.0]
 [6535000.0 7050000.0]
 [850000.0 849900.0]
 [2100000.0 4995000.0]
 [2030000.0 1449000.0]
 [2000000.0 3950000.0]
 [2500000.0 3200000.0]
 [3400000.0 2050000.0]
 [1550000.0 2000000.0]
 [4300000.0 1650000.0]
 [1895000.0 1250000.0]
 [1195000.0 1450000.0]
 [1490000.0 1795000.0]
 [780000.0 945000.0]
 [3936945.0 3800000.0]
 [3650000.0 2000000.0]
 [1410000.0 1995000.0]
 [1625000.0 1600000.0]
 [3545000.0 3575000.0]
 [2695000.0 3799000.0]
 [6950000.0 6700000.0]
 [7250000.0 1650000.0]
 [6795000.0 6795000.0]
 [2295000.0 2950000.0]
 [2550000.0 3095000.0]
 [4775000.0 3600000.0]
 [998000.0 2895000.0]
 [7250000.0 3400000.0]
 [2950000.0 2399000.0]
 [1350000.0 1650000.0]
 [2550000.0 1295000.0]
 [3650000.0 3395000.0]
 [3795000.0 3250000.0]
 [6995000.0 8100000.0]
 [1425000.0 1150000.0]
 [2350000.0 3190000.0]
 [12500000.0 11025000.0]
 [2195000.0 3550000.0]
 [3950000.0 4575000.0]
 [4100000.0 6995000.0]
 [2695000.0 7500000.0]
 [8850000.0 6100000.0]
 [2750000.0 2600000.0]
 [6760000.0 6760000.0]
 [3999000.0 3999000.0]
 [2149000.0 1790000.0]
 [12900000.0 14250000.0]
 [1345000.0 1850000.0]]

In [20]:
df4 = Y_pred1 - Y_test
df4.sort()
df4

array([-22867000.1, -18867000.1, -13617000.1, -11367000.1, -11217000.1,
       -10392000.1, -9667000.1, -9367000.1, -8617000.1, -8367000.1,
       -7467000.1, -6867000.1, -6867000.1, -6867000.1, -6617000.1,
       -6417000.1, -6362000.1, -6317000.1, -6317000.1, -6257000.1,
       -6162000.1, -6127000.1, -6067000.1, -5917000.1, -5717000.1,
       -5662000.1, -5617000.1, -5467000.1, -5367000.1, -5117000.1,
       -5017000.1, -4967000.1, -4867000.1, -4812000.1, -4362000.1,
       -4262000.1, -4167000.1, -4067000.1, -3942000.1, -3867000.1,
       -3867000.1, -3862000.1, -3817000.1, -3617000.1, -3517000.1,
       -3442000.1, -3366000.1, -3362000.1, -3317000.1, -3317000.1,
       -3262000.1, -3217000.1, -3167000.1, -3166000.1, -3162000.1,
       -3067000.1, -3062000.1, -2967000.1, -2962000.1, -2942000.1,
       -2917000.1, -2867000.1, -2866000.1, -2862000.1, -2856500.1,
       -2767000.1, -2767000.1, -2762000.1, -2717000.1, -2692000.1,
       -2662000.1, -2662000.1, -2657000.1, -2617000.1, -2617000.1,
       -2617000.1, -2617000.1, -2567000.1, -2567000.1, -2567000.1,
       -2562000.1, -2557000.1, -2467000.1, -2462000.1, -2317000.1,
       -2317000.1, -2317000.1, -2266000.1, -2262000.1, -2262000.1,
       -2242000.1, -2167000.1, -2116000.1, -2092000.1, -2062000.1,
       -2017000.1, -2017000.1, -1992000.1, -1967000.1, -1917000.1,
       -1862000.1, -1847000.1, -1767000.1, -1766000.1, -1712000.1,
       -1567000.1, -1517000.1, -1492000.1, -1452000.1, -1417000.1,
       -1367000.1, -1367000.1, -1367000.1, -1362000.1, -1362000.1,
       -1347000.1, -1267000.1, -1252000.1, -1223000.1, -1217000.1,
       -1217000.1, -1217000.1, -1167000.1, -1162000.1, -1162000.1,
       -1162000.1, -1157000.1, -1117000.1, -1092000.1, -1087000.1,
       -1067000.1, -1066000.1, -1062000.1, -1062000.1, -1017000.1,
       -1017000.1, -1017000.1, -1017000.1, -1007000.1, -967000.1,
       -962000.1, -917000.1, -892000.1, -867000.1, -866000.1, -846000.1,
       -842000.1, -817000.1, -817000.1, -817000.1, -816000.1, -762000.1,
       -717000.1, -717000.1, -717000.1, -667000.1, -666000.1, -662000.1,
       -647000.1, -617000.1, -567000.1, -566000.1, -517000.1, -517000.1,
       -467000.1, -366000.1, -317000.1, -316949.1, -312000.1,
       -242000.09999999998, -216900.09999999998, -162000.09999999998,
       37999.90000000002], dtype=object)